version: '3'
services:
  node:
    container_name: school-api
    image: node:8-alpine
    restart: always
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    depends_on:
      - mysql
    ports:
      - "8080:3000"
    command: sh -c './wait-for mysql:3306 -- npm start'