version: '3'
services:
  mysql:
    container_name: school-mysql
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=school
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=yDb.435rT